--!strict

--[[
    Bugs.OS GeneratorConfig
    Food Harvesters + Condiments configuration.
    Generated from BugsOS_Food_Generator_Icon_Prompts_With_Condiments (1).xlsx.

    User-facing UI should say Harvester and Condiment.
    Internal names keep Generator compatibility for existing services.
]]

local GeneratorConfig = {}

GeneratorConfig.Classes = {
    {
        id = "snack",
        displayName = "Snack",
        sortOrder = 1,
    },
    {
        id = "fruit",
        displayName = "Fruit",
        sortOrder = 2,
    },
    {
        id = "sandwich",
        displayName = "Sandwich",
        sortOrder = 3,
    },
    {
        id = "dessert",
        displayName = "Dessert",
        sortOrder = 4,
    },
    {
        id = "picnic",
        displayName = "Picnic",
        sortOrder = 5,
    },
    {
        id = "garden",
        displayName = "Garden",
        sortOrder = 6,
    },
    {
        id = "feast",
        displayName = "Feast",
        sortOrder = 7,
    },
}

GeneratorConfig.Harvesters = {
    cracker_crate = {
        id = "cracker_crate",
        displayName = "Cracker Crate",
        classId = "snack",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 5,
        condimentSlots = 2,
        buff = nil,
        buffValue = 0,
        buffText = "None",
        cost = 100,
        sortOrder = 1,
    },
    cookie_tin = {
        id = "cookie_tin",
        displayName = "Cookie Tin",
        classId = "snack",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 8,
        condimentSlots = 2,
        buff = "OfflineEarnings",
        buffValue = 0.1,
        buffText = "10% Offline Earnings",
        cost = 1500,
        sortOrder = 2,
    },
    chip_basket = {
        id = "chip_basket",
        displayName = "Chip Basket",
        classId = "snack",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 6,
        condimentSlots = 2,
        buff = "ClickPower",
        buffValue = 0.05,
        buffText = "5% Click Power",
        cost = 800,
        sortOrder = 3,
    },
    pretzel_bowl = {
        id = "pretzel_bowl",
        displayName = "Pretzel Bowl",
        classId = "snack",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 12,
        condimentSlots = 1,
        buff = "FoodPerSec",
        buffValue = 0.08,
        buffText = "8% Food/Sec",
        cost = 1200,
        sortOrder = 4,
    },
    granola_jar = {
        id = "granola_jar",
        displayName = "Granola Jar",
        classId = "snack",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 7,
        condimentSlots = 2,
        buff = "CoinEarnings",
        buffValue = 0.05,
        buffText = "5% Coin Earnings",
        cost = 1000,
        sortOrder = 5,
    },
    popcorn_pail = {
        id = "popcorn_pail",
        displayName = "Popcorn Pail",
        classId = "snack",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 4,
        condimentSlots = 2,
        buff = "MysteryDropRate",
        buffValue = 0.08,
        buffText = "8% Mystery Drop Rate",
        cost = 1800,
        sortOrder = 6,
    },
    berry_basket = {
        id = "berry_basket",
        displayName = "Berry Basket",
        classId = "fruit",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 30,
        condimentSlots = 3,
        buff = "BugChance",
        buffValue = 0.15,
        buffText = "15% Bug Chance",
        cost = 8000,
        sortOrder = 1,
    },
    apple_cart = {
        id = "apple_cart",
        displayName = "Apple Cart",
        classId = "fruit",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 20,
        condimentSlots = 4,
        buff = "CondimentOutput",
        buffValue = 0.2,
        buffText = "20% Condiment Output",
        cost = 12000,
        sortOrder = 2,
    },
    citrus_crate = {
        id = "citrus_crate",
        displayName = "Citrus Crate",
        classId = "fruit",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 25,
        condimentSlots = 3,
        buff = "NectarChance",
        buffValue = 0.1,
        buffText = "10% Nectar Chance",
        cost = 15000,
        sortOrder = 3,
    },
    banana_bundle = {
        id = "banana_bundle",
        displayName = "Banana Bundle",
        classId = "fruit",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 28,
        condimentSlots = 3,
        buff = "FoodPerSec",
        buffValue = 0.08,
        buffText = "8% Food/Sec",
        cost = 9000,
        sortOrder = 4,
    },
    melon_basket = {
        id = "melon_basket",
        displayName = "Melon Basket",
        classId = "fruit",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 35,
        condimentSlots = 2,
        buff = "ClickPower",
        buffValue = 0.1,
        buffText = "10% Click Power",
        cost = 10000,
        sortOrder = 5,
    },
    fruit_scale = {
        id = "fruit_scale",
        displayName = "Fruit Scale",
        classId = "fruit",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 18,
        condimentSlots = 4,
        buff = "OfflineEarnings",
        buffValue = 0.1,
        buffText = "10% Offline Earnings",
        cost = 11000,
        sortOrder = 6,
    },
    sandwich_station = {
        id = "sandwich_station",
        displayName = "Sandwich Station",
        classId = "sandwich",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 200,
        condimentSlots = 4,
        buff = "BugChance",
        buffValue = 0.15,
        buffText = "15% Rare Chance",
        cost = 50000,
        sortOrder = 1,
    },
    picnic_cooler = {
        id = "picnic_cooler",
        displayName = "Picnic Cooler",
        classId = "sandwich",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 120,
        condimentSlots = 6,
        buff = "ClickPower",
        buffValue = 0.2,
        buffText = "20% Click Power",
        cost = 100000,
        sortOrder = 2,
    },
    deli_tray = {
        id = "deli_tray",
        displayName = "Deli Tray",
        classId = "sandwich",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 160,
        condimentSlots = 5,
        buff = "FoodPerSec",
        buffValue = 0.1,
        buffText = "10% Food/Sec",
        cost = 150000,
        sortOrder = 3,
    },
    lunchbox_stack = {
        id = "lunchbox_stack",
        displayName = "Lunchbox Stack",
        classId = "sandwich",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 140,
        condimentSlots = 5,
        buff = "CoinEarnings",
        buffValue = 0.12,
        buffText = "12% Coin Earnings",
        cost = 60000,
        sortOrder = 4,
    },
    sub_cart = {
        id = "sub_cart",
        displayName = "Sub Cart",
        classId = "sandwich",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 180,
        condimentSlots = 4,
        buff = "OfflineEarnings",
        buffValue = 0.1,
        buffText = "10% Offline Earnings",
        cost = 75000,
        sortOrder = 5,
    },
    toast_press = {
        id = "toast_press",
        displayName = "Toast Press",
        classId = "sandwich",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 110,
        condimentSlots = 6,
        buff = "FoodPerSec",
        buffValue = 0.08,
        buffText = "8% Food/Sec",
        cost = 85000,
        sortOrder = 6,
    },
    cupcake_stand = {
        id = "cupcake_stand",
        displayName = "Cupcake Stand",
        classId = "dessert",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 900,
        condimentSlots = 7,
        buff = "BugChance",
        buffValue = 0.25,
        buffText = "25% Rare Chance",
        cost = 900000,
        sortOrder = 1,
    },
    ice_cream_cart = {
        id = "ice_cream_cart",
        displayName = "Ice Cream Cart",
        classId = "dessert",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 1200,
        condimentSlots = 6,
        buff = "CondimentOutput",
        buffValue = 0.3,
        buffText = "30% Condiment Output",
        cost = 1000000,
        sortOrder = 2,
    },
    candy_machine = {
        id = "candy_machine",
        displayName = "Candy Machine",
        classId = "dessert",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 600,
        condimentSlots = 9,
        buff = "CoinEarnings",
        buffValue = 0.2,
        buffText = "20% Coin Earnings",
        cost = 1500000,
        sortOrder = 3,
    },
    donut_box = {
        id = "donut_box",
        displayName = "Donut Box",
        classId = "dessert",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 800,
        condimentSlots = 7,
        buff = "OfflineEarnings",
        buffValue = 0.4,
        buffText = "40% Offline Earnings",
        cost = 2000000,
        sortOrder = 4,
    },
    brownie_tray = {
        id = "brownie_tray",
        displayName = "Brownie Tray",
        classId = "dessert",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 950,
        condimentSlots = 7,
        buff = "FoodPerSec",
        buffValue = 0.12,
        buffText = "12% Food/Sec",
        cost = 900000,
        sortOrder = 5,
    },
    pudding_cup_stack = {
        id = "pudding_cup_stack",
        displayName = "Pudding Cup Stack",
        classId = "dessert",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 700,
        condimentSlots = 8,
        buff = "BugChance",
        buffValue = 0.2,
        buffText = "20% Bug Chance",
        cost = 1200000,
        sortOrder = 6,
    },
    picnic_table = {
        id = "picnic_table",
        displayName = "Picnic Table",
        classId = "picnic",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 4000,
        condimentSlots = 9,
        buff = "AllEarnings",
        buffValue = 0.15,
        buffText = "15% All Earnings",
        cost = 5000000,
        sortOrder = 1,
    },
    grill_station = {
        id = "grill_station",
        displayName = "Grill Station",
        classId = "picnic",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 5000,
        condimentSlots = 8,
        buff = "MysteryDropRate",
        buffValue = 0.2,
        buffText = "20% Mystery Drop Rate",
        cost = 10000000,
        sortOrder = 2,
    },
    buffet_spread = {
        id = "buffet_spread",
        displayName = "Buffet Spread",
        classId = "picnic",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 3500,
        condimentSlots = 10,
        buff = "OfflineEarnings",
        buffValue = 0.5,
        buffText = "50% Offline Earnings",
        cost = 15000000,
        sortOrder = 3,
    },
    picnic_blanket = {
        id = "picnic_blanket",
        displayName = "Picnic Blanket",
        classId = "picnic",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 4500,
        condimentSlots = 8,
        buff = "ClickPower",
        buffValue = 0.15,
        buffText = "15% Click Power",
        cost = 6000000,
        sortOrder = 4,
    },
    bbq_cooler = {
        id = "bbq_cooler",
        displayName = "BBQ Cooler",
        classId = "picnic",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 3800,
        condimentSlots = 9,
        buff = "BugChance",
        buffValue = 0.25,
        buffText = "25% Bug Chance",
        cost = 8000000,
        sortOrder = 5,
    },
    snack_umbrella = {
        id = "snack_umbrella",
        displayName = "Snack Umbrella",
        classId = "picnic",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 5500,
        condimentSlots = 8,
        buff = "FoodPerSec",
        buffValue = 0.12,
        buffText = "12% Food/Sec",
        cost = 12000000,
        sortOrder = 6,
    },
    greenhouse_pod = {
        id = "greenhouse_pod",
        displayName = "Greenhouse Pod",
        classId = "garden",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 20000,
        condimentSlots = 12,
        buff = "CondimentOutput",
        buffValue = 0.25,
        buffText = "25% Condiment Output",
        cost = 50000000,
        sortOrder = 1,
    },
    nectar_harvester = {
        id = "nectar_harvester",
        displayName = "Nectar Harvester",
        classId = "garden",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 25000,
        condimentSlots = 11,
        buff = "AllEarnings",
        buffValue = 0.12,
        buffText = "12% All Earnings",
        cost = 100000000,
        sortOrder = 2,
    },
    compost_reactor = {
        id = "compost_reactor",
        displayName = "Compost Reactor",
        classId = "garden",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 15000,
        condimentSlots = 14,
        buff = "OfflineEarnings",
        buffValue = 0.15,
        buffText = "15% Offline Earnings",
        cost = 200000000,
        sortOrder = 3,
    },
    sprout_rack = {
        id = "sprout_rack",
        displayName = "Sprout Rack",
        classId = "garden",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 22000,
        condimentSlots = 12,
        buff = "CoinEarnings",
        buffValue = 0.15,
        buffText = "15% Coin Earnings",
        cost = 60000000,
        sortOrder = 4,
    },
    pollen_mill = {
        id = "pollen_mill",
        displayName = "Pollen Mill",
        classId = "garden",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 18000,
        condimentSlots = 13,
        buff = "BugChance",
        buffValue = 0.3,
        buffText = "30% Bug Chance",
        cost = 80000000,
        sortOrder = 5,
    },
    mushroom_planter = {
        id = "mushroom_planter",
        displayName = "Mushroom Planter",
        classId = "garden",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 30000,
        condimentSlots = 14,
        buff = nil,
        buffValue = 0,
        buffText = "None",
        cost = 120000000,
        sortOrder = 6,
    },
    royal_banquet = {
        id = "royal_banquet",
        displayName = "Royal Banquet",
        classId = "feast",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 50000,
        condimentSlots = 20,
        buff = nil,
        buffValue = 0,
        buffText = "None",
        cost = 300000000,
        sortOrder = 1,
    },
    golden_buffet = {
        id = "golden_buffet",
        displayName = "Golden Buffet",
        classId = "feast",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 34000,
        condimentSlots = 15,
        buff = "CoinEarnings",
        buffValue = 0.25,
        buffText = "25% Coin Earnings",
        cost = 250000000,
        sortOrder = 2,
    },
    queens_table = {
        id = "queens_table",
        displayName = "Queen's Table",
        classId = "feast",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 28000,
        condimentSlots = 17,
        buff = "OfflineEarnings",
        buffValue = 0.25,
        buffText = "25% Offline Earnings",
        cost = 300000000,
        sortOrder = 3,
    },
    colony_feast_hall = {
        id = "colony_feast_hall",
        displayName = "Colony Feast Hall",
        classId = "feast",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 30000,
        condimentSlots = 16,
        buff = "FoodPerSec",
        buffValue = 0.2,
        buffText = "20% Food/Sec",
        cost = 350000000,
        sortOrder = 4,
    },
    nectar_fountain = {
        id = "nectar_fountain",
        displayName = "Nectar Fountain",
        classId = "feast",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 24000,
        condimentSlots = 12,
        buff = "NectarChance",
        buffValue = 0.2,
        buffText = "20% Nectar Chance",
        cost = 400000000,
        sortOrder = 5,
    },
    grand_harvest_altar = {
        id = "grand_harvest_altar",
        displayName = "Grand Harvest Altar",
        classId = "feast",
        category = "standard",
        icon = nil,
        baseFoodPerSec = 40000,
        condimentSlots = 16,
        buff = "AllEarnings",
        buffValue = 0.15,
        buffText = "15% All Earnings",
        cost = 1000000000,
        sortOrder = 6,
    },
}

GeneratorConfig.Condiments = {
    ketchup = {
        id = "ketchup",
        displayName = "Ketchup",
        icon = nil,
        foodPerSec = 1,
        cost = 25,
        sortOrder = 1,
    },
    mayo = {
        id = "mayo",
        displayName = "Mayo",
        icon = nil,
        foodPerSec = 3,
        cost = 150,
        sortOrder = 2,
    },
    lettuce = {
        id = "lettuce",
        displayName = "Lettuce",
        icon = nil,
        foodPerSec = 10,
        cost = 600,
        sortOrder = 3,
    },
    tomato = {
        id = "tomato",
        displayName = "Tomato",
        icon = nil,
        foodPerSec = 20,
        cost = 2500,
        sortOrder = 4,
    },
    ranch = {
        id = "ranch",
        displayName = "Ranch",
        icon = nil,
        foodPerSec = 50,
        cost = 12000,
        sortOrder = 5,
    },
    truffle_oil = {
        id = "truffle_oil",
        displayName = "Truffle Oil",
        icon = nil,
        foodPerSec = 100,
        cost = 55000,
        sortOrder = 6,
    },
    wasabi_cream = {
        id = "wasabi_cream",
        displayName = "Wasabi Cream",
        icon = nil,
        foodPerSec = 250,
        cost = 250000,
        sortOrder = 7,
    },
    garlic_parmesan = {
        id = "garlic_parmesan",
        displayName = "Garlic Parmesan",
        icon = nil,
        foodPerSec = 600,
        cost = 1200000,
        sortOrder = 8,
    },
    cosmic_butter = {
        id = "cosmic_butter",
        displayName = "Cosmic Butter",
        icon = nil,
        foodPerSec = 1500,
        cost = 6000000,
        sortOrder = 9,
    },
    meteor_dust_seasoning = {
        id = "meteor_dust_seasoning",
        displayName = "Meteor Dust Seasoning",
        icon = nil,
        foodPerSec = 4000,
        cost = 30000000,
        sortOrder = 10,
    },
    eternal_marinade = {
        id = "eternal_marinade",
        displayName = "Eternal Marinade",
        icon = nil,
        foodPerSec = 10000,
        cost = 150000000,
        sortOrder = 11,
    },
    infinite_spice = {
        id = "infinite_spice",
        displayName = "Infinite Spice",
        icon = nil,
        foodPerSec = 25000,
        cost = 3000000000,
        sortOrder = 12,
    },
}

-- Backwards-compatible alias for old code paths.
GeneratorConfig.Generators = GeneratorConfig.Harvesters

function GeneratorConfig.GetClass(classId: string)
    for _, classInfo in ipairs(GeneratorConfig.Classes) do
        if classInfo.id == classId then
            return classInfo
        end
    end
    return nil
end

function GeneratorConfig.GetHarvester(harvesterId: string)
    return GeneratorConfig.Harvesters[harvesterId]
end

function GeneratorConfig.GetGenerator(generatorId: string)
    return GeneratorConfig.GetHarvester(generatorId)
end

function GeneratorConfig.GetCondiment(condimentId: string)
    return GeneratorConfig.Condiments[condimentId]
end

function GeneratorConfig.GetHarvestersForClass(classId: string, category: string?)
    local result = {}
    for _, harvester in pairs(GeneratorConfig.Harvesters) do
        if harvester.classId == classId and (category == nil or harvester.category == category) then
            table.insert(result, harvester)
        end
    end
    table.sort(result, function(a, b)
        return (a.sortOrder or 0) < (b.sortOrder or 0)
    end)
    return result
end

function GeneratorConfig.GetStandardHarvestersForClass(classId: string)
    return GeneratorConfig.GetHarvestersForClass(classId, "standard")
end

function GeneratorConfig.GetSkinHarvestersForClass(classId: string)
    return GeneratorConfig.GetHarvestersForClass(classId, "skin")
end

function GeneratorConfig.GetCondimentsSorted()
    local result = {}
    for _, condiment in pairs(GeneratorConfig.Condiments) do
        table.insert(result, condiment)
    end
    table.sort(result, function(a, b)
        return (a.sortOrder or 0) < (b.sortOrder or 0)
    end)
    return result
end

function GeneratorConfig.GetBestAffordableCondiment(coins: number)
    local best = nil
    for _, condiment in pairs(GeneratorConfig.Condiments) do
        if condiment.cost <= coins then
            if best == nil
                or condiment.foodPerSec > best.foodPerSec
                or (condiment.foodPerSec == best.foodPerSec and condiment.cost > best.cost) then
                best = condiment
            end
        end
    end
    return best
end

return GeneratorConfig
